name: Build rmf-HT docker images

on:
  push:
    branches: ['cgh_ot_main', 'SBH-71-Add-auto-build-for-rmf-ros2']
  pull_request:
    branches: ['cgh_ot_main', 'SBH-71-Add-auto-build-for-rmf-ros2']
  schedule:
    - cron: "08 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set branch name and git commit SHA
      run: | 
        echo "branch_name=$(echo ${GITHUB_REF_NAME} | tr '/' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "git_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: build rosdep 
      run: | 
        docker build --no-cache=true -t rosdep:latest -f build/builder-rosdep.Dockerfile .
        docker tag rosdep:latest hopetechnik/rosdep:latest

    - name: check out source code
      run:  mkdir build/rmf-src && vcs import build/rmf-src < build/rmf.repos
      
    - name: Build and tag rmf-ros2 Docker image
      run: |  
        docker build --no-cache=true -t rmf-ros2:latest -f build/Dockerfile .
        docker tag rmf-ros2:latest hopetechnik/rmf-core:${{ env.git_sha_short }}
        docker tag rmf-ros2:latest hopetechnik/rmf-core:${{ env.branch_name }}-${{ env.git_sha_short }}
        docker tag rmf-ros2:latest hopetechnik/rmf-core:latest
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push images to docker hub 
      run: | 
        docker push hopetechnik/rmf-core:${{ env.git_sha_short }}
        docker push hopetechnik/rosdep:latest
        docker push hopetechnik/rmf-core:latest
        docker push hopetechnik/rmf-core:${{ env.branch_name }}-${{ env.git_sha_short }}

    - name: clean up local docker images 
      run: | 
        docker rmi hopetechnik/rmf-core:${{ env.git_sha_short }}
        docker rmi hopetechnik/rmf-core:latest 
        docker rmi hopetechnik/rmf-core:${{ env.branch_name }}-${{ env.git_sha_short }} 
        docker rmi rmf-core:latest 
        docker rmi rosdep:latest
        docker rmi hopetechnik/rosdep:latest

    - name: remove latest files
      run: rm -rf build/rmf-src

    - name: Clean up Docker system
      run: docker system prune -f
