name: Build rmf-HT docker images

on:
  push:
    branches: ['cgh_ot_main', 'SC2-805-Cherry-pick-fixes-from-open-rmf-for-mutex-group-release-and-emergency-pullover-for-ROS2-2']
  pull_request:
    branches: ['cgh_ot_main']
  schedule:
    - cron: "08 0 * * *"
  workflow_dispatch:

jobs:
  build_ros_dep:
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set branch name and git commit SHA
      run: | 
        echo "branch_name=$(echo ${GITHUB_REF_NAME} | tr '/' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "git_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check if image exist
      id: is_image_exist
      uses: KerberosMorphy/docker-exist-action@v1.1.1
      with:
        registry: docker.io
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        image: hopetechnik/rosdep:latest

    - name: build rosdep 
      if: ((!steps.is_image_exist.outputs.image_exist))
      run: | 
        docker build --no-cache=true -t rosdep:latest -f build/builder-rosdep.Dockerfile .
        docker tag rosdep:latest hopetechnik/rosdep:latest

    - name: Push the ros dep latest
      if: ((!steps.is_image_exist.outputs.image_exist))
      run: docker push hopetechnik/rosdep:latest

    - name: clean up 
      if: ((!steps.is_image_exist.outputs.image_exist))
      run: |
        docker rmi rosdep:latest hopetechnik/rosdep:latest
        docker system prune -f
  
  build_rmf_core:
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set branch name and git commit SHA
      run: | 
        echo "branch_name=$(echo ${GITHUB_REF_NAME} | tr '/' '_' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "git_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get latest rosdep and rmf core from docker hub 
      run: |  
        docker pull hopetechnik/rosdep:latest
        docker tag hopetechnik/rosdep:latest rosdep:latest

    - name: check out source code
      run:  mkdir build/rmf-src && vcs import build/rmf-src < build/rmf.repos
      
    - name: Build rmf-ros2 Docker image
      run: |
        docker build --no-cache=true -t rmf-ros2:latest -f build/Dockerfile .
        docker tag rmf-ros2:latest hopetechnik/rmf-core:${{ env.git_sha_short }}
        docker tag rmf-ros2:latest hopetechnik/rmf-core:${{ env.branch_name }}-${{ env.git_sha_short }}
        docker tag rmf-ros2:latest hopetechnik/rmf-core:latest

    - name: Push rmf-ros2 images
      run: |
        docker push hopetechnik/rmf-core:${{ env.git_sha_short }}
        docker push hopetechnik/rosdep:latest
        docker push hopetechnik/rmf-core:latest
        docker push hopetechnik/rmf-core:${{ env.branch_name }}-${{ env.git_sha_short }}

    - name: clean up local images 
      run: |
        docker rmi hopetechnik/rmf-core:${{ env.git_sha_short }} || true
        docker rmi hopetechnik/rmf-core:latest || true
        docker rmi hopetechnik/rmf-core:${{ env.branch_name }}-${{ env.git_sha_short }} || true
        docker rmi rmf-core:latest || true
    
    - name: Remove local rmf-ros2 latest image
      run: |
        docker rmi rosdep:latest || true
        docker rmi hopetechnik/rosdep:latest 

    - name: remove latest files
      run: rm -rf build/rmf-src

    - name: Clean up Docker system
      run: docker system prune -f
